In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]], columns=['cgpa','profile_score','lpa'])

In [3]:
df.head()

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [5]:
model = Sequential()

model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 2)                 6         
                                                                 
 dense_1 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [7]:
model.get_weights()

[array([[-0.29703403, -0.7756751 ],
        [-1.1684545 ,  0.15907443]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.2376652 ],
        [-0.30363536]], dtype=float32),
 array([0.], dtype=float32)]

In [8]:
new_weights = [np.array([[0.1,0.1], 
                         [0.1,0.1]], dtype = np.float32),
               np.array([0.,0.], dtype = np.float32),
               np.array([[0.1],
                         [0.1]], dtype = np.float32),
               np.array([0.], dtype = np.float32)]

In [9]:
model.set_weights(new_weights)

In [10]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [11]:
optimizer = keras.optimizers.Adam(learning_rate = 0.001)
model.compile(loss = 'mean_squared_error', optimizer = optimizer)

In [12]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values,epochs = 75, verbose = 1, batch_size = 1)

Epoch 1/75
4/4 [==============================] - 1s 5ms/step - loss: 27.9023
Epoch 2/75
4/4 [==============================] - 0s 4ms/step - loss: 27.5646
Epoch 3/75
4/4 [==============================] - 0s 3ms/step - loss: 27.2346
Epoch 4/75
4/4 [==============================] - 0s 4ms/step - loss: 26.9016
Epoch 5/75
4/4 [==============================] - 0s 4ms/step - loss: 26.5787
Epoch 6/75
4/4 [==============================] - 0s 5ms/step - loss: 26.1878
Epoch 7/75
4/4 [==============================] - 0s 3ms/step - loss: 25.8391
Epoch 8/75
4/4 [==============================] - 0s 5ms/step - loss: 25.4691
Epoch 9/75
4/4 [==============================] - 0s 4ms/step - loss: 25.0317
Epoch 10/75
4/4 [==============================] - 0s 3ms/step - loss: 24.6455
Epoch 11/75
4/4 [==============================] - 0s 4ms/step - loss: 24.2273
Epoch 12/75
4/4 [==============================] - 0s 4ms/step - loss: 23.8452
Epoch 13/75
4/4 [==============================] - 0s 4ms/ste

In [13]:
model.get_weights()

[array([[0.37365276, 0.37365276],
        [0.36571708, 0.36571708]], dtype=float32),
 array([0.27238202, 0.27238202], dtype=float32),
 array([[0.3730017],
        [0.3730017]], dtype=float32),
 array([0.2048067], dtype=float32)]