Wonder what species of IRIS do these flowers belong to?

Import the Libraries

In [1]:
# Import the Libraries

# Loading the Library with the iris dataset
from sklearn.datasets import load_iris

# Loading scikit's random forest classifier library
from sklearn.ensemble import RandomForestClassifier

#Loading Pandas & Numpy
import pandas as pd
import numpy as np
from sklearn import metrics
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
#Setting random seed 
np.random.seed(0)

In [ ]:
# Creating an Object called iris with iris dataset
# iris = load_iris()
# df = pd.DataFrame(iris.data, columns= iris.feature_names)
# df.head()

#from dataset file of iris.csv
iris = pd.read_csv('Iris.csv')
# Displaying first 5 rows of our dataset
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
# Displaying last five rows of our dataset
iris.tail()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica

In [ ]:
# Now we gonna add one column

# Creating Test and Train Data
iris['is_train'] = np.random.uniform(0,1, len(iris)) <=.75

#Displaying the top 5 rows
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species  \
0   1            5.1           3.5            1.4           0.2  Iris-setosa   
1   2            4.9           3.0            1.4           0.2  Iris-setosa   
2   3            4.7           3.2            1.3           0.2  Iris-setosa   
3   4            4.6           3.1            1.5           0.2  Iris-setosa   
4   5            5.0           3.6            1.4           0.2  Iris-setosa   

   is_train  
0      True  
1      True  
2      True  
3      True  
4      True

In [ ]:
# Creating the data frames with test rows and training rows
train, test = iris[iris['is_train'] == True], iris[iris['is_train'] == False]

# Show the number of observation for the test and training data frames
print('Number of observation in the training dataset : ', len(train))
print('Number of observation in the test dataset : ', len(test))

Number of observation in the training dataset :  118
Number of observation in the test dataset :  32


In [ ]:
# Creating a list of the Feature column's names
features = iris.columns[1:5]

# View Features
print(features )

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')


In [ ]:
# Converting each species name into digits
y = pd.factorize(train['Species'])[0]

#viewing target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# Creating a Random Forest Classifier
clf = RandomForestClassifier(n_jobs = 2, random_state = 0)

# Training the classifier
print(clf.fit(train[features], y))

RandomForestClassifier(n_jobs=2, random_state=0)


In [ ]:
# Applying the trained classifier to the test
test[features]
clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
# Viewing the predicted probabilities of the first 10 observations
clf.predict_proba(test[features])[10:20]

array([[1.  , 0.  , 0.  ],
       [0.99, 0.01, 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 0.67, 0.33],
       [0.  , 1.  , 0.  ],
       [0.  , 0.82, 0.18],
       [0.  , 0.03, 0.97],
       [0.  , 0.42, 0.58],
       [0.  , 0.99, 0.01],
       [0.  , 0.96, 0.04]])

In [ ]:
# Mapping names for the plants for each predicted plant class
preds = iris.Species[clf.predict(test[features])]


# View the PREDICTED species for the first five observations
preds[0:5]

0    Iris-setosa
0    Iris-setosa
0    Iris-setosa
0    Iris-setosa
0    Iris-setosa
Name: Species, dtype: object

In [ ]:
# Viewing the Actual species for the first five observations
test['Species'].head()

7     Iris-setosa
8     Iris-setosa
10    Iris-setosa
13    Iris-setosa
17    Iris-setosa
Name: Species, dtype: object

In [ ]:
# Create Confusion matrix
# cm  = metrics.confusion_matrix(test['Species'],preds)
# # Visualizing the confusion matrix
# plt.figure(figsize=(9,9))
# sns.heatmap(cm,annot = True, fmt = ".3f", linewidths = .5, square = True, cmap = 'Blues_r')
# plt.ylabel('Actual Label')
# plt.xlabel('Predicted Label')
# # all_sample_title = 'Accuracy Score : {0}'.format(score)
# #plt.title(all_sample_title, size = 15)
# prin
pd.crosstab(test['Species'], preds, rownames = ['Actual Species'], colnames=['Predicted Species'])

Empty DataFrame
Columns: []
Index: []

In [ ]:
xd = iris.Species[clf.predict([[5.1,	3.5,	1.4,	0.2],[4.6,	3.1,	1.5,	0.2]])]

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
clf.predict([[5.1,	3.5,	1.4,	0.2],[4.6,	3.1,	1.5,	0.2]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0, 0])