In [6]:
# nd - array
# GPU Support
# Computational graph / Backpropagation
# immutable


import tensorflow as tf

In [7]:
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

In [10]:
x = tf.constant(4, shape = (1,1), dtype = tf.float32)
print(x)

tf.Tensor([[4.]], shape=(1, 1), dtype=float32)


In [11]:
y = tf.constant([[1,2,3],[4,5,6]])
print(y)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [13]:
z = tf.ones((3,3))
print(z)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [14]:
a = tf.zeros((3,3))
print(a)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]], shape=(3, 3), dtype=float32)


In [15]:
identity_matrix = tf.eye(3)
print(identity_matrix)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [17]:
random_value = tf.random.normal((3,3), mean = 0, stddev = 1)
print(random_value)

tf.Tensor(
[[-0.00735164  0.95234704  1.0080415 ]
 [ 0.48665577 -0.90707546  2.3533099 ]
 [ 0.5766911  -1.0616628  -1.3652169 ]], shape=(3, 3), dtype=float32)


In [19]:
uniform_distribution_random = tf.random.uniform((3,3), minval = 0, maxval = 1)
print(uniform_distribution_random)

tf.Tensor(
[[0.28222072 0.1262753  0.19396484]
 [0.5185633  0.78115904 0.39802206]
 [0.13729537 0.03930593 0.94982564]], shape=(3, 3), dtype=float32)


In [20]:
rangevalue = tf.range(10)
print(rangevalue)

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [22]:
casting = tf.cast(rangevalue,dtype = tf.float32)
print(casting)

tf.Tensor([0. 1. 2. 3. 4. 5. 6. 7. 8. 9.], shape=(10,), dtype=float32)


In [25]:
# performing addition
num1 = tf.constant([1,2,3])
num2 = tf.constant([4,5,6])

add = tf.add(num1,num2)
# print(add)
add

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 9], dtype=int32)>

In [27]:
num1 = tf.random.normal((2,2))
num2 = tf.random.normal((2,2))

mul = tf.matmul(num1,num2)
mul

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.7332842, -1.2864674],
       [ 0.9936184,  1.425264 ]], dtype=float32)>

In [30]:
# slicing and indexing
x = tf.constant([[1,2,3,4],[5,6,7,8]])
print(x[0])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [33]:
print(x[:,0])

tf.Tensor([1 5], shape=(2,), dtype=int32)


In [34]:
print(x[0,:])

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [35]:
print(x[0:])

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32)


In [36]:
print(x[0, 1:3])

tf.Tensor([2 3], shape=(2,), dtype=int32)


In [37]:
print(x[1,1:3])

tf.Tensor([6 7], shape=(2,), dtype=int32)


In [38]:
x = tf.random.normal((2,3))
print(x)

tf.Tensor(
[[ 0.48692545  0.30906868 -0.40106562]
 [ 1.4074792  -0.05635244  1.2253891 ]], shape=(2, 3), dtype=float32)


In [41]:
# reshaping x
x = tf.reshape(x,(3,2))
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.48692545,  0.30906868],
       [-0.40106562,  1.4074792 ],
       [-0.05635244,  1.2253891 ]], dtype=float32)>

In [42]:
x = tf.reshape(x,(6))
x

<tf.Tensor: shape=(6,), dtype=float32, numpy=
array([ 0.48692545,  0.30906868, -0.40106562,  1.4074792 , -0.05635244,
        1.2253891 ], dtype=float32)>

In [44]:
x = tf.reshape(x,(-1,2))
x

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.48692545,  0.30906868],
       [-0.40106562,  1.4074792 ],
       [-0.05635244,  1.2253891 ]], dtype=float32)>

In [48]:
x = tf.random.normal((2,3))

In [49]:
x = x.numpy()

In [50]:
type(x)

numpy.ndarray

In [52]:
x = tf.convert_to_tensor(x)
type(x)

tensorflow.python.framework.ops.EagerTensor

In [53]:
x = tf.constant("raftaar")
x

<tf.Tensor: shape=(), dtype=string, numpy=b'raftaar'>

In [54]:
x = tf.constant(['raftaar','dont','love','someone','you','arent','meant','for','anyone'])
x

<tf.Tensor: shape=(9,), dtype=string, numpy=
array([b'raftaar', b'dont', b'love', b'someone', b'you', b'arent',
       b'meant', b'for', b'anyone'], dtype=object)>